name = "find-your-strengths-worker"
main = "src/index.ts"
compatibility_date = "2025-09-13" 

[site]
bucket = "./dist"
fallback = "index.html" # <--- ADD THIS LINE!

[[d1_databases]]
binding = "DB"
database_name = "find-strengths"
database_id = "8cd76b9c-d506-4b36-9908-5baf1bf07cb4"